name: 'docker-build'

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2

        -
            name: Pull submodules
            run: git submodule update --init

        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v1

        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

        -
            name: Login to DockerHub
            uses: docker/login-action@v1 
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

        -
            name: Build
            uses: docker/build-push-action@v2
            with:
              context: .
              platforms: linux/amd64,linux/arm64
              push: true
              tags: bitest/acfunlive:latest

        -
            name: Delete workflow runs
            uses: GitRML/delete-workflow-runs@main
            with:
              retain_days: 1
              keep_minimum_runs: 3
